### ISSUE TITLE
[Feature] Excluding options and attributes in the filter menu

### ISSUE THREAD

**Issue by vvasiloi** [BitBagCommerce/SyliusElasticsearchPlugin#1]
Having this configurable from the parameters means every new exclusion/inclusion requires a change in the parameters and (usually) a deploy. That's not something an admin is (usually) able to do.
Make Options and Attributes exclusion from filters dynamically configurable from code, admin panel and API.
Possible implementation: extra flag on the respective entities.

**Comment by bitbager** [comment]
Thank you! We will take that in mind after the stable release. Leaving it as opened.

**Comment by bitbager** [comment]
For now, we didn't find a need for this feature. That being said, I am closing this issue.
