### ISSUE TITLE
Is it possible to switch between 'Match' and 'Terms'?

### ISSUE THREAD

**Issue by JordivdB** [BitBagCommerce/SyliusElasticsearchPlugin#101]
Hello,

Is is possible to use Terms (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html) instead of Match (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html).

I couldn't find any config to do this. 

Thanks in advance.

**Comment by crackgm** [comment]
You can decorate QueryBuilders: https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/tree/master/src/QueryBuilder
Some of them already use Terms and other Match

**Comment by JordivdB** [comment]
Thanks!
