### ISSUE TITLE
No menu items when root category code is not 'category'

### ISSUE THREAD

**Issue by euperia** [BitBagCommerce/SyliusElasticsearchPlugin#106]
I started with a fresh installation of Sylius 1.6.5 and added my own taxonomies, starting with a root category with a code of 'nav'.

There were no errors when running the `bin/console fo:el:po` command but there was no menu shown on the site.  

Changing the root category code to 'category' fixed this.

**Comment by damonsson** [comment]
Because to display them in the menu, must have this code
