### ISSUE TITLE
Elasticsearch 7.x support?

### ISSUE THREAD

**Issue by kdckrs** [BitBagCommerce/SyliusElasticsearchPlugin#108]
Are you guys planning to support Elasticsearch 7.x anytime soon? If there any ETA?

Thanks!

**Comment by vwatel** [comment]
I would also be interested to know if there is a plan about this.
Thanks!

**Comment by patrick477** [comment]
it is currently impossible, we use FOSElasticaBundle which supports maximum version 6.x

**Comment by damonsson** [comment]
Looks like we are close https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1569

**Comment by nikkuexe** [comment]
@damonsson Looks like FOSElasticaBundle is now 7.x.

**Comment by damonsson** [comment]
Still in Beta right now

**Comment by senghe** [comment]
The ES7 is supported by version 2.0.1 and above: https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/releases/tag/v2.0.1

The PR where it's been implemented:
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/pull/194
