### ISSUE TITLE
Rendering the shop products list exception

### ISSUE THREAD

**Issue by kuzyk** [BitBagCommerce/SyliusElasticsearchPlugin#11]
When I go to the products list page throw exception:
`
Controller "bitbag_sylius_elasticsearch_plugin.controller.action.shop.list_products" cannot be fetched from the container because it is private. Did you forget to tag the service with "controller.service_arguments"?
`
sylius: 1.2

**Comment by bitbager** [comment]
Hi there! Are you using Sylius 1.2 with Symfony 4?

**Comment by kuzyk** [comment]
Hi
yes.

**Comment by bitbager** [comment]
CC @damonsson, @patrick477, we must adjust this plugin to support Symfony 4. @kuzyk, we will take care of it in the incoming days. Expect a new version to appear on weekend.

**Comment by bitbager** [comment]
Should be fixed now 🎉
