### ISSUE TITLE
Duplicate class?

### ISSUE THREAD

**Issue by gabiudrescu** [BitBagCommerce/SyliusElasticsearchPlugin#110]
I see that these two classes are basically the same. Is there any reason I am missing here for these two classes to exist or one of them should be deleted?

https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/master/src/Context/ProductProductAttributesContext.php
vs
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/master/src/Context/ProductAttributesContext.php

see tests for them here:
 - https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/master/spec/Context/ProductProductAttributesContextSpec.php
 - https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/master/spec/Context/ProductAttributesContextSpec.php

**Comment by vvasiloi** [comment]
I guess one is for defined product attributes and another is for assigned product attributes (many-to-many mapping).

**Comment by patrick477** [comment]
it looks like a mistake, we will remove it until next release :)

**Comment by pavol-tk** [comment]
There was more than 10 releases after 27 Apr 2020, but that class is still there. It should be removed. And also `ProductProductAttributesContextSpec` should be removed.

So, two files to delete:
```
src/Context/ProductProductAttributesContext.php
spec/Context/ProductProductAttributesContextSpec.php
```
