### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by nicosomb** [BitBagCommerce/SyliusElasticsearchPlugin#117]
Hello! 

Do you plan to release a new tag soon please? 
We're waiting for the updated french translation. 

Have a nice day!

**Comment by damonsson** [comment]
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/releases/tag/v1.6.0 enjoy

**Comment by marhub** [comment]
What's your release flow ?  
I'm also interested in pushing something that's on master but is not yet tagged and would like to know what to expect.

**Comment by marhub** [comment]
@damonsson

**Comment by damonsson** [comment]
If you need a new tag from a master, let us know, we can release. Now we are working on version 2.0 primarily. Which will be a big milestone.
