### ISSUE TITLE
Attributes with 'null' values break the whole facet

### ISSUE THREAD

**Issue by mvriel** [BitBagCommerce/SyliusElasticsearchPlugin#118]
In a project of ours, I have a facet on an attribute that is optional. But since we import it from another PIM, the attribute is added to a product but with a value of null (while it is of type text).

When building the choices for this facet, Symfony detects that there is a key that is not a string (the null) and decides to renumber every key. So instead of the actual attribute values, you get 0,1,2,3,4,etc.

Which does not work .. We combated this by decorating the ProductAttributesFilterType form and adding an array_filter in after the array_unique around choices.

This will make it impossible to filter on those empty values, but since elasticsearch cannot search on empty values anyway; there was little else possible.

The only alternative we saw, but was seemingly fickle, was to add conversions in the ProductAttributesMapper and AttributeBuilder to detect the combination of a 'text' attribute and the value 'null'; and replace that with something like 'unknown'. We could not do this on import, because then that value would be shown on the product detail page, and that is not an option.

**Comment by leszczuu** [comment]
With current version - v4.0.2 - it seems this null values no longer break filters.
Missing values are not shown in filters as option, but filtering works correctly - if You filter on value that is missing, product with missing value will not be shown in results.
