### ISSUE TITLE
Make fuzziness configurable

### ISSUE THREAD

**Issue by mvriel** [BitBagCommerce/SyliusElasticsearchPlugin#125]
Is it possible to make the fuzziness at https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/master/src/QueryBuilder/SearchProductsQueryBuilder.php#L65 configurable or injectable? I would like to manipulate this value but need to duplicate this whole builder now to do that

**Comment by senghe** [comment]
I've already passed this on our developers team :)

**Comment by senghe** [comment]
It's done and merged to master :)
