### ISSUE TITLE
UI - Filters cannot be used on mobile (Safari & Chrome, Android & iOS)

### ISSUE THREAD

**Issue by gabiudrescu** [BitBagCommerce/SyliusElasticsearchPlugin#127]
See video below:
![Screen Recording 2020-06-16 at 21 38 57](https://user-images.githubusercontent.com/5156054/84814683-7e21bd00-b01a-11ea-8bd3-cb183f73ce08.gif)

**Comment by jcgdjob** [comment]
Try this:
change
<div class="ui fluid vertical menu">
to
<div class="ui fluid">

**Comment by leszczuu** [comment]
I've tested just with Android and Chrome but with currenc version - v4.0.2  - deployed on https://b2b-suite.demo.sylius.com/en_US/products-list/jeans/men it seems to work on mobile.
![Screenshot_2024-08-22-10-30-03-46_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/f92bb491-7d31-4b3e-bc49-c4d911744fef)
![Screenshot_2024-08-22-10-30-20-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/7d175f66-6130-4580-aa69-efead51ee12f)
