### ISSUE TITLE
Extend 'Search' to include attributes on Sylius 1.6

### ISSUE THREAD

**Issue by JordivdB** [BitBagCommerce/SyliusElasticsearchPlugin#128]
Hi,

Is there a possibility to extend the search through the searchbar to include (certain) attributes as well? I'm still on Sylius 1.6, so i use version 1.5.6. 

Thanks.

**Comment by bybilvanis** [comment]
Same here.

**Comment by ibasaw** [comment]
i use sylius 1.6 because of php 7.2.
I am curious to know why search is not available for 1.5, but only for v1.6 ?

**Comment by mpysiak** [comment]
Closing, Sylius 1.6 is not supported
