### ISSUE TITLE
Updating the product position does not update the index

### ISSUE THREAD

**Issue by pcmsystemsltd** [BitBagCommerce/SyliusElasticsearchPlugin#129]
Sylius version: ^1.6
Plugin version:  1.6.0

If the user updates the product position the event listener does not trigger and the index gets outdated. We are currently re-indexing at midnight running the command to resolve this in the meanwhile.

**Comment by nithiz** [comment]
+1

**Comment by nithiz** [comment]
Thanks @crackgm for the PR code, i used it and changed one thing to make sure all products are updated. It can be a little slow though but i'd rather have correct slow results than incorrect fast results: ```

        $products = $this->productRepository->findAllByTaxonCode($productTaxon->getTaxon()->getCode());
        foreach ($products as $product) {
            $this->resourceRefresher->refresh($product, 'fos_elastica.object_persister.bitbag_shop_product.default');
        }
