### ISSUE TITLE
$this->optionProperty property only used in the constructor

### ISSUE THREAD

**Issue by Florian-Merle** [BitBagCommerce/SyliusElasticsearchPlugin#131]
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/5e5cac9d44fa2a0e451f3ad2fe0f7f0655570824/src/PropertyBuilder/OptionTaxonsBuilder.php#L47

This property can be removed from `OptionTaxonsBuilder` and its service definition

**Comment by kptLucek** [comment]
@Florian-Merle may you please close issue if #143 fixes your problem?
Thanks
