### ISSUE TITLE
Excluding certain products

### ISSUE THREAD

**Issue by olia-bn** [BitBagCommerce/SyliusElasticsearchPlugin#135]
Is there a way to exclude certain products from results?

**Comment by kptLucek** [comment]
Hello there!

Yes, it is, as you may know, one of this bundle's requirements is [FOSElasticaBundle](https://github.com/FriendsOfSymfony/FOSElasticaBundle), and based on it's documentation - [Check this out](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/indexes.md#testing-if-an-object-should-be-indexed).

Remember, that you'll need to override `bitbag_shop_product` index mapping.

**Comment by mpysiak** [comment]
Hi, thanks @kptLucek for your help
