### ISSUE TITLE
Problem with filter

### ISSUE THREAD

**Issue by twin-elements** [BitBagCommerce/SyliusElasticsearchPlugin#138]
I installed your plugin according to the instructions and plugged in Elasticsearch.
When I go to /{_ locale}/product-list/{slug} I can see products. Options for these products are in the sidebar. But when I try to search for any of these options, I don't get any results. What could be the reason?

**Comment by Lowcost-dev** [comment]
Hi,

It's maybe related to : https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/issues/100
What's your options ?

**Comment by crackgm** [comment]
@kolarian Can you please provide more details (options examples), so we can reproduce this issue?
