### ISSUE TITLE
'composer require bitbag/elasticsearch-plugin' fails

### ISSUE THREAD

**Issue by linnit** [BitBagCommerce/SyliusElasticsearchPlugin#141]
To replicate:

```
composer create-project sylius/sylius-standard test-sylius
cd test-sylius
composer require bitbag/elasticsearch-plugin
```

The error:

```
Script cache:clear returned with error code 1
!!  
!!  In DefinitionErrorExceptionPass.php line 54:
!!                                                                                 
!!    You have requested a non-existent parameter "bitbag_es_shop_name_property_p  
!!    refix".                                                                      
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

Is there any fix for this?

**Comment by euperia** [comment]
I had this but put it down to a slow internet connection but I guess thats incorrect if others are getting the problem.

A workaround is to add the routing include to your `config/packages/_sylius.yaml` file and then run the composer install command.

```
# config/packages/_sylius.yaml
imports:
    ...
    - { resource: "@BitBagSyliusElasticsearchPlugin/Resources/config/config.yml" }
```

Or try running `composer require bitbag/elasticsearch-plugin --no-scripts`

**Comment by kptLucek** [comment]
Hello and thanks for report.

I've successfully replicated your issue, however have you followed installation documentation?

Based on documentation: [LINK](https://github.com/BitBagCommerce/SyliusElasticsearchPlugin)

```yaml
# config/packages/_sylius.yaml
imports:
    ...
    - { resource: "@BitBagSyliusElasticsearchPlugin/Resources/config/config.yml" }
```

Once this resource got added everything seems to work like expected
