### ISSUE TITLE
Attribute with boolean value is incorrectly queried as .keyword

### ISSUE THREAD

**Issue by olia-bn** [BitBagCommerce/SyliusElasticsearchPlugin#152]
I have a bunch of attributes in my project that are checkboxes (have boolean value) and trying to filter by them returns no results.

After debugging the problem I've noticed that the elastic query uses .keyword, but that is not correct for boolean fields as far as I know (it is correct for the string-values attributes)

In terms of elastic queries: this plugin uses the following:
```
      "should": [
        {
          "term": {
            "attribute_e89.keyword": {
              "value": "1"
            }
          }
        }
      ]
```

but this does not work. It should be doing the following (for boolean values):

```
      "should": [
        {
          "term": {
            "attribute_e89": {
              "value": true
            }
          }
        }
      ]
```

This is because the boolean attribute translates to boolean value in elastica:
```
      {
        "_index" : "shop_products_dev",
        "_type" : "default",
        "_id" : "2630",
        "_score" : 0.031748697,
        "_source" : {
          "enabled" : true,
          "name_nl_nl" : "Lightning-USB Adapter voor iPhone",
          "attribute_e84" : [
            true
          ],
          "attribute_e89" : [
            true
          ],
         ...
```

**Comment by stargen** [comment]
Hi, this issue is on same place of code
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/issues/35

**Comment by rafalmal** [comment]
Looks like issue was fixed already, print screen with boolean attribute and correcy search result below.
![image](https://user-images.githubusercontent.com/105425505/230590475-8c73faa0-2c96-42db-be59-337384ee5ca0.png)
