### ISSUE TITLE
Error on a fresh install

### ISSUE THREAD

**Issue by thibmonier** [BitBagCommerce/SyliusElasticsearchPlugin#165]
On a sylius 1.9 fresh install I have the following error (I tried stable and dev versions)

`The service "bitbag_sylius_elasticsearch_plugin.controller.action.shop.list_products" has a dependency on a non-existent service "tem
  plating". Did you mean one of these: "sylius.templating.helper.convert_money", "sylius.templating.helper.adjustment", "sylius.templat
  ing.helper.format_money", "sylius.templating.helper.currency", "sylius.templating.helper.locale", "sylius.templating.helper.inventory
  ", "sylius.templating.helper.product_variants_prices", "sylius.templating.helper.price", "sylius.templating.helper.variant_resolver",
   "sylius.templating.helper.checkout_steps", "sylius.templating.helper.grid", "sylius.templating.helper.bulk_action_grid", "sonata.blo
  ck.templating.helper", "liip_imagine.templating.filter_extension"?`

**Comment by justRau** [comment]
I am getting the same on Sylius 1.9.3 on PHP 7.4 after running `composer require bitbag/elasticsearch-plugin`.

**Comment by cuongphphanoi** [comment]
I am facing issue when installed
` The service "bitbag_sylius_elasticsearch_plugin.controller.action.shop.search" has a dependency on a non-existent service "fos_elastica.finder.bitbag_shop_product.default".`

**Comment by justRau** [comment]
@cuongphphanoi did you follow https://github.com/BitBagCommerce/SyliusElasticsearchPlugin#installation? Seems like config import in `config/packages/_sylius.yaml` is missing.

**Comment by cuongphphanoi** [comment]
@justRau yes it already imported.

I set in `config/services` like this:
`transformer.products:
        class: FOS\ElasticaBundle\Doctrine\ORM\ElasticaToModelTransformer
        arguments:
            $objectClass: '%sylius.model.product.class%'

    transformer.option.taxons:
        class: FOS\ElasticaBundle\Doctrine\ORM\ElasticaToModelTransformer
        arguments:
            $objectClass: '%sylius.model.product_option.class%'
    
    transformer.attribute.taxons:
        class: FOS\ElasticaBundle\Doctrine\ORM\ElasticaToModelTransformer
        arguments:
            $objectClass: '%sylius.model.product_attribute.class%'
    
    fos_elastica.finder.bitbag_shop_product.default:
        class: FOS\ElasticaBundle\Finder\TransformedFinder
        arguments:
            $searchable: '@fos_elastica.index.bitbag_shop_product'
            $transformer: '@transformer.products'

    fos_elastica.finder.bitbag_option_taxons.default:
        class: FOS\ElasticaBundle\Finder\TransformedFinder
        arguments:
            $searchable: '@fos_elastica.index.bitbag_option_taxons'
            $transformer: '@transformer.option.taxons'

    fos_elastica.finder.bitbag_attribute_taxons.default:
        class: FOS\ElasticaBundle\Finder\TransformedFinder
        arguments:
            $searchable: '@fos_elastica.index.bitbag_attribute_taxons'
            $transformer: '@transformer.attribute.taxons'`

and then it's work :)

**Comment by 0mars** [comment]
@justRau do you have any other solution, I'm gonnaa dive into installing 2.x since I need ES7 anyway

**Comment by thibmonier** [comment]
I dove into the code and it appears that the service configuration use a depracated call to templating (depracated since Sf4)

I was able to install everything with the minimum stability set to dev, I also removed all the calls to the templating service in controller.xml and shop.xml.

Now I didn't finish the work but I have to modify the controllers also.

**Comment by justRau** [comment]
Here are the patches that I currently use to make v2.0.0-beta1 work on Sylius v1.9.3. 
I think BitBag\SyliusElasticsearchPlugin\Controller\Action\Shop\SearchAction should be patched as well, but have not encountered the errors yet, so did not patch it yet.
I will create a PR some day, if it's not fixed.

[bitbag-elasticsearch-plugin-src-controller-action-shop-listproductsaction-php.txt](https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/files/6544036/bitbag-elasticsearch-plugin-src-controller-action-shop-listproductsaction-php.txt)
[bitbag-elasticsearch-plugin-src-resources-config-services-controller-shop-xml.txt](https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/files/6544037/bitbag-elasticsearch-plugin-src-resources-config-services-controller-shop-xml.txt)
[bitbag-elasticsearch-plugin-src-resources-config-services-controller-xml.txt](https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/files/6544038/bitbag-elasticsearch-plugin-src-resources-config-services-controller-xml.txt)

**Comment by justRau** [comment]
Actually, looks like this issue is already fixed in `master` branch: https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/commit/53db5a48a81baf97135bbc63046a6b7687bb323a

**Comment by senghe** [comment]
The 2.x branch has been removed, so the #168 is not current. The 2.x version is currently on master, so - as it's fixed on master - I'm closing the issue.
