### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by lruozzi9** [BitBagCommerce/SyliusElasticsearchPlugin#185]
This plugin does not support PHP 8.0.
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/51a2b1edc280bfcfa6f206a98a38163a6500cd4a/composer.json#L8

**Comment by yanlep** [comment]
In "bitbag/elasticsearch-plugin/src/QueryBuilder/ContainsNameQueryBuilder.php" I just replaced :
"use Elastica\Query\Match;" by "use Elastica\Query\MatchQuery;"
and
"$nameQuery = new Match();" by "$nameQuery = new MatchQuery();"

and it works with PHP 8.0(.14 in my case) as Elastica\Query\Match only extends MatchQuery.

**Comment by tavy315** [comment]
Should be solved by https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/pull/179

**Comment by senghe** [comment]
Hi @lruozzi9,

The PHP 8.0 is supported since v2.0.1: https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/releases/tag/v2.0.1
