### ISSUE TITLE
[Question] Search including sub categories

### ISSUE THREAD

**Issue by jcgdjob** [BitBagCommerce/SyliusElasticsearchPlugin#19]
Hi,

  I would like to update the search including sub categories (i.e., if I search the root, all products should return). Should I override BitBag SyliusElasticsearchPlugin code? 

  When I run php bin/console debug:config, I cannot find the "Extension alias". How can I change the code?

Thanks!

**Comment by bitbager** [comment]
The easiest way to achieve this behavior is to add all taxons to the product, including parent taxons with the checkbox in admin panel.

If that's not enough for you, you will need to override the product taxons property builder service.

https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/master/src/PropertyBuilder/ProductTaxonsBuilder.php

https://symfony.com/doc/current/service_container/service_decoration.html

**Comment by jcgdjob** [comment]
Thanks! It works.

Just to share what I have done:
#service.yml
    app.bitbag.syliuselasticsearchplugin.propertybuilder.producttaxonsbuilder:
        decorates: bitbag_sylius_elasticsearch_plugin.property_builder.product_taxons
        class: AppBundle\PropertyBuilder\ProductTaxonsBuilder
        arguments:
            - "@bitbag_sylius_elasticsearch_plugin.property_builder.mapper.product_taxons"
            - "%bitbag_es_shop_product_taxons_property%"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_subscriber }
