### ISSUE TITLE
Variants showing up, despite being disabled or having no inventory

### ISSUE THREAD

**Issue by hriad** [BitBagCommerce/SyliusElasticsearchPlugin#190]
Hello,

I'm experiencing a strange issue. Disabling a product variant, or setting it's inventory value to 0; still shows the variant in the results. I've tried to reindex but that didn't fix the problem.

I'm using bitbag/elasticsearch-plugin v1.7.3 on Sylius v1.10.5

**Comment by piotrleo** [comment]
By reindexing you mean fos:elastica:populate? Because in my case disabling product doesn't have effect but after populate it's updating correctly. My research about this issue is still in progress because it should be done automatically, by listeners. Please give me feedback if it's connected to your issue too.
If you have any more info, post it and I guess we'll be able to figure out what's wrong. You can also attach some screenshots with exact problem, so I can relate to it better.

**Comment by hriad** [comment]
Yes, by re-indexing, I meant `fos:elastica:populate`. At first I thought it was a listener issue too; but when modifying products I had changes reflected immediately in my index; so the problem was somewhere else.

In the end, I fixed my problem by decoration [bitbag_sylius_elasticsearch_plugin.property_builder.option](https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/master/src/PropertyBuilder/OptionBuilder.php#L44)

```php
private function resolveProductOptions(ProductInterface $product, Document $document): void
    {
        foreach ($product->getEnabledVariants() as $productVariant) {
            foreach ($productVariant->getOptionValues() as $productOptionValue) {
                $optionCode = $productOptionValue->getOption()->getCode();
                $index = $this->optionNameResolver->resolvePropertyName($optionCode);
                $options = $document->has($index) ? $document->get($index) : [];
                $value = $this->stringFormatter->formatToLowercaseWithoutSpaces($productOptionValue->getValue());
                $options[] = $value;
                if ($this->availabilityChecker->isStockAvailable($productVariant)) {
                    $document->set($index, array_values(array_unique($options)));
                }
            }
        }
    }
```

Notice the call to `getEnabledVariants`  instead of the original `getVariants` and the usage of `isStockAvailable` to filter out out of stock items.
