### ISSUE TITLE
Excluding options and attributes in the filter menu not working

### ISSUE THREAD

**Issue by SofianeMerouane** [BitBagCommerce/SyliusElasticsearchPlugin#199]
Hello I have filled in the options and attributes to exclude in the list of filters like this:
parameters:
    locale: en_US
    bitbag_es_excluded_filter_options: ['jeans_size', 't_shirt_size']
    bitbag_es_excluded_filter_attributes: ['t_shirt_brand']

But despite that I still have the filters displayed.
The client would like to administer the filters to be displayed on the facets, I would like to make the filters more dynamic but I don't know the best way to do it can someone help me please.

And thank you for all the team working on this plugin

**Comment by leszczuu** [comment]
With version 4.x this feature is handled by new facet filters, and can be configured as described in 
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin?tab=readme-ov-file#excluding-options-and-attributes-in-the-filter-menu
or by manually configuring filters and disabling autodiscovery.

I've checked autodiscovery feature and now it works fine:
![image](https://github.com/user-attachments/assets/6e3b414c-1fbb-419e-a5c0-93984dfb923d)
![image](https://github.com/user-attachments/assets/21b17477-23c0-44fe-bf9f-011937979fb4)
