### ISSUE TITLE
Options filter doesn't work

### ISSUE THREAD

**Issue by czende** [BitBagCommerce/SyliusElasticsearchPlugin#2]
Hi, thanks for this plugin! Attribute filter and its combinations works well, but options filter doesn't seem to work 😞 
![screen shot 2018-03-16 at 12 08 35](https://user-images.githubusercontent.com/5628485/37517867-1fd65c0a-2913-11e8-9916-30c079061762.png)
![screen shot 2018-03-16 at 12 09 03](https://user-images.githubusercontent.com/5628485/37517868-21a04d48-2913-11e8-89ad-288b06dfde51.png)

**Comment by bitbager** [comment]
Yes, that was because of our last improvements to the query builder. Should be fine now 🙂
