### ISSUE TITLE
bitbag-autocomplete-search.css

### ISSUE THREAD

**Issue by TELLO0815** [BitBagCommerce/SyliusElasticsearchPlugin#207]
search.html.twig is looking for 
`bundles/bitbagsyliuselasticsearchplugin/css/bitbag-autocomplete-search.css`
but css is missing?
must be bitbag-elasticsearch-shop.css and js?

TELLO

**Comment by mpysiak** [comment]
Hi,

This issue was fixed in https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/issues/217
