### ISSUE TITLE
ElasticSearch 7.0 support

### ISSUE THREAD

**Issue by Jelmer7** [BitBagCommerce/SyliusElasticsearchPlugin#208]
In the README.md on master it is said this plugin supports ElasticSearch 7.0, but in the latest release (v2.1.0) it says it does not.

https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/140faf3a7c99f6d4260a3ed44b8a05ca9a92516f/README.md?plain=1#L59

https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/5848787fbc287e1cd4cd782b1a9d456121fd5e60/README.md?plain=1#L59

We tried making it work with ElasticSearch 7.0 anyway but could not make it work. 
Is 7.0 supported or not? And if not when is it planned for release?

Thanks!

**Comment by senghe** [comment]
Hi @Jelmer7

The ES7 is supported by version 2.0.1 and above: https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/releases/tag/v2.0.1

The PR where it's been implemented:
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/pull/194
