### ISSUE TITLE
Add Sylius 1.12 support

### ISSUE THREAD

**Issue by tidall87** [BitBagCommerce/SyliusElasticsearchPlugin#212]
Hi, do you plan to add compatibility with Sylius 1.12 (Symfony 6 and Api Platform 2.7)?

**Comment by senghe** [comment]
Hi @tidall87, yes, we do. I'll be back soon with more information :)

**Comment by valentin-harrang** [comment]
👍 🙏

**Comment by senghe** [comment]
Hi, we support Sylius v1.12 from version [v3.0.0](https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/releases/tag/v3.0.0) :tada:
