### ISSUE TITLE
No Images in ListProductsByPartialNameAction.php

### ISSUE THREAD

**Issue by TELLO0815** [BitBagCommerce/SyliusElasticsearchPlugin#213]
I use Sylius 1.11.10.
There are no images found in the controller:
BitBag\SyliusElasticsearchPlugin\Controller\Action\Api\ListProductsByPartialNameAction.php

```
 /** @var TransformerInterface */
 private $productImageTransformer;
......

$this->productImageTransformer->transform($product)
```

ImagesAwareInterface

**Comment by TELLO0815** [comment]
Just if other people have the same problem:
it works if you marke one picture as main.
Or you change in the ImageTransformer.php to $productThumbnails = $product->getImages();

**Comment by mpysiak** [comment]
Hi,

Thanks @TELLO0815 for pointing out, product images must be marked as `main` to show
