### ISSUE TITLE
Taxon move not working

### ISSUE THREAD

**Issue by eca11** [BitBagCommerce/SyliusElasticsearchPlugin#22]
When I move product to another main taxon, then taxon list not reindex and product is still visible in old taxon.

Any ideas?

**Comment by patrick477** [comment]
you can override the `setPosition` method in `ProductTaxon`, for example:

public function setPosition(?int $position): void
{
        parent::setPosition($position);

        $this->getProduct()->setUpdatedAt(new \DateTime());
}

how to change product update date will update the index
