### ISSUE TITLE
No results when searching for products with multiple values of channels, product-taxons

### ISSUE THREAD

**Issue by AnD-FLuX** [BitBagCommerce/SyliusElasticsearchPlugin#249]
The problem lies in configuring product search and displaying them on the product-list route or simply when searching for a product. Using standard mapping settings, I have the following versions:

BitBag Elasticsearch Plugin: 3.3.2
Sylius: 1.12.18

The main issues I'm facing involve debugging queries to products-taxon. It's similar to what I've observed with channels: if product_taxons has only one value, it successfully returns the product. However, when there are two or more product_taxons values, search results do not display. Interestingly, using the product-list route with a change in query to product_taxons.keyword starts returning the relevant products. (With channels, the same problem persists.)

Please provide advice or possible solutions to address these issues. I would appreciate any help or recommendations.

**Comment by AnD-FLuX** [comment]
<img width="482" alt="Screenshot 2024-07-04 at 15 35 11" src="https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/assets/72544430/c9cd4633-37d1-4d0a-b29d-c3b245bca7fc">

<img width="875" alt="image" src="https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/assets/72544430/bc2f3346-03b1-4bbf-9661-cda33f096d01">
This is dump of query on products-list route


<img width="805" alt="image" src="https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/assets/72544430/fbee205b-dcb7-421b-a817-e99af3fc18c6">
If add ".keyword" to the fields where more than 1 value - we find this product

Please tell me why so, maybe there are options how to fix it?

**Comment by senghe** [comment]
Hi @AnD-FLuX, thanks for highlighting an issue :)

We've rewritten our search queries with v4.0.0. Could you install it on your instance and see whether the issue exists there? I hope it is not. I think you can check this by running the clean plugin from `tests/Application` directory. Installing v4.0.0 on your project might potentially result Sylius version compatibility issues etc.

I hope the v4.0.0 solves your issues :)
