### ISSUE TITLE
Please update readme installation instructions for latest v1.3 of sylius

### ISSUE THREAD

**Issue by Vinit-Koshti** [BitBagCommerce/SyliusElasticsearchPlugin#28]
Please update readme installation instructions for latest v1.3 of sylius @bitbager @pamil @patrick477 @stefandoorn

**Comment by Vinit-Koshti** [comment]
> Why am I tagged in here?

Sorry Sir, I am facing some issue setting up SyliusElasticsearchPlugin, in the symfony profiler I can see elastica, but filters are not appearing on the page. 
--------------------------------------------------------------------------
bitbager [8 hours ago]
You need to override the routing for the shop products list. It uses a different path. Read the installation guide carefully.
------------------------------------------------------------
I got some hint from @bitbager  but still unable to figure out the issue

![screenshot from 2018-11-23 10-21-32](https://user-images.githubusercontent.com/16951071/48929024-c5ad9900-ef0a-11e8-84ef-c119667fc3d4.png)

**Comment by bitbager** [comment]
You're not using the right path. The proper path you should be targeting can be found here: https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/blob/master/src/Resources/config/routing.yml. Import the routing on the bottom of your routing.yml, this way you will get the default product list overriden by this route.
