### ISSUE TITLE
Notice: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by AxelDeneu** [BitBagCommerce/SyliusElasticsearchPlugin#56]
I ended up with this notice on Sylius 1.4.
The error says that there is a problem with the type casting in the method : `convertFromString`.
Currently, this method does this : 
```php
private function convertFromString(string $price): int
{
    return (int) round($price * 100, 2);
}
```

I solved this problem by casting the string as an integer to be sure that the numeric value will be ok. This is the resulting method : 
```php
private function convertFromString(string $price): int
{
    return (int) round((int) $price * 100, 2);
}
```

Am I the only one experiencing this problem?
Do you think I should make a pull request?

**Comment by bitbager** [comment]
Fixed, thanks!
