### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by czende** [BitBagCommerce/SyliusElasticsearchPlugin#6]
Hi, I was trying to index my Sylius options names with czech or even polish names (starts with Č or Ł) and `ruflin/elastica/lib/Elastica/JSON.php` is still throwing this error. I was googling it, but still can't find solution. Any hint? Thx!

**Comment by bitbager** [comment]
To be honest, I have no clue. I guess this question should be asked on https://github.com/ruflin/Elastica.
