### ISSUE TITLE
[Feature] Site wide search

### ISSUE THREAD

**Issue by mmenozzi** [BitBagCommerce/SyliusElasticsearchPlugin#66]
Hi,
I started [here](https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/compare/master...mmenozzi:sitewide-search?expand=1) the site-wide search feature.

It's not complete yet but it already works having a search box form on all pages. It searches even on description and short description product fields.

Could you please have a first look and tell me if I'm on the right way or not?

**Comment by damonsson** [comment]
Hi @mmenozzi it's a huge contribution to the development of this plugin, thank you very much. We have to test it on a few live projects and we will give some feedback, finally I hope we will merge.

**Comment by bybilvanis** [comment]
Any updates?

**Comment by damonsson** [comment]
@bybilvanis it's merged to master. Works stable, so we'll release that soon.

**Comment by damonsson** [comment]
released
