### ISSUE TITLE
Introducing analyzers for the dash-problem

### ISSUE THREAD

**Issue by peterukena** [BitBagCommerce/SyliusElasticsearchPlugin#71]
I think fixing the dash-problem can be done by defining an analyzer for the fields.

No analyzer means "standard_analyzer" which actually splits indexed and searched terms with a dash - using the "whitespace" analyzer for those fields would mitigate that problem entirely.

Sadly I dont have the time to dig into this plugin or fos_elastica too much to integrate it, especially since I dont really know how this plugin is defining all its type-properties so I dont know where to put the analyzer config.

This is just a hint for the devs - maybe this is an easy thing to fix for you guys. 

More information here: https://discuss.elastic.co/t/query-string-search-containing-a-dash-has-unexpected-results/20622/2

**Comment by leszczuu** [comment]
linked to issue with problem, closing this one, will move solution to readme.
