### ISSUE TITLE
Bug : error JS

### ISSUE THREAD

**Issue by mkic** [BitBagCommerce/SyliusElasticsearchPlugin#72]
Hi,
I'm getting this error on the product list page : 

```
bitbag-autocomplete-search.js:8 Uncaught TypeError: $(...).search is not a function
    at w.fn.init.autocompleteSearch (bitbag-autocomplete-search.js:8)
    at VM739 t-shirts:528
```

Any direction on how to resolve ? I use a custom theme, and I also had to copy the whole public part of the plugin in public/_bundle/theme/mytheme

Thansk guys

**Comment by rechengehirn** [comment]
Have you installed the assets?
`bin/console assets:install`

**Comment by bitbager** [comment]
It's either a problem with assets or your custom UI implementation that does not use Semantic UI's assets.
