### ISSUE TITLE
Elasticsearch data is not updating after product edit. You have to populate manually. 

### ISSUE THREAD

**Issue by ssuheesh** [BitBagCommerce/SyliusElasticsearchPlugin#74]
Elasticsearch data is not updating after product edit. We have to populate manually.

**Comment by ssuheesh** [comment]
Editting T-shirt "ea" product name to T-shirt "ea" cum and searching with 'cum' keyword. Should be 2 products in T-shirt/men category, but shows only one product. After bin/console fo:el:po, search shows 2 products.
![image](https://user-images.githubusercontent.com/33533025/64502389-836a1280-d2f8-11e9-97e1-f1877b7260ae.png)
![image](https://user-images.githubusercontent.com/33533025/64502465-d47a0680-d2f8-11e9-9463-aade9d89e032.png)

**Comment by bitbager** [comment]
Should be fixed now od dev-master.
