### ISSUE TITLE
ProductAttributes - more than 10 default ES

### ISSUE THREAD

**Issue by TELLO0815** [BitBagCommerce/SyliusElasticsearchPlugin#75]
I think for the most of shops is 10 attributes not enough. 

I think 50 or 100 (to $excludedAttributes some) would be better solution?
 
BitBag\SyliusElasticsearchPlugin\Finder\ProductAttributesFinder.php

`return $this->attributesFinder->find($query, 50);  `

**Comment by mpysiak** [comment]
Hi,

I am closing the issue. The attributes limit is 20 now
