### ISSUE TITLE
ProductAttributes also from all Channels in Filter

### ISSUE THREAD

**Issue by TELLO0815** [BitBagCommerce/SyliusElasticsearchPlugin#76]
If there are more than one channel and they have same taxonId, they all listed. I guess its better to list only what's in the channel available?

**Comment by bitbager** [comment]
Could you provide a user story?

**Comment by McOffsky** [comment]
@bitbager I think this screenshot would explain it all better then longest user story :) Each book have single value in "Print year". This is screenshot from one of the channels, it shows only products for specific category and channel. Yet facets are build based on ALL products in this category, for all channels. 
![image](https://user-images.githubusercontent.com/3004015/111481465-483d7080-8733-11eb-9e11-2e37e5903c18.png)

**Comment by leszczuu** [comment]
Related to https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/issues/73
After rewrite in current version filters are generated only based on elasticsearch data, from results.
