### ISSUE TITLE
Argument 5 (price) issue

### ISSUE THREAD

**Issue by TELLO0815** [BitBagCommerce/SyliusElasticsearchPlugin#77]
Looks like other people have the same issue when using autocomplete:

`Argument 5 passed to BitBag\SyliusElasticsearchPlugin\Controller\Response\DTO\Item::__construct() must be of the type string, null given, called in /var/www/html/xxxxx/vendor/bitbag/elasticsearch-plugin/src/Controller/Action/Api/ListProductsByPartialNameAction.php on line 72`

Any idea?

**Comment by bitbager** [comment]
How about decoration and injection of ChannelContext?

**Comment by leszczuu** [comment]
no longer applicable, current version - v4.0.2 filters this result by channels.
![image](https://github.com/user-attachments/assets/0bb77edf-217a-4e27-b6b1-920bb4492bb5)
