### ISSUE TITLE
Cannot install due to version conflict

### ISSUE THREAD

**Issue by jcgdjob** [BitBagCommerce/SyliusElasticsearchPlugin#8]
I have installed Sylius 1.1.6 and having problem when installing SyliusElasticsearchPlugin:
  Problem 1
    - Conclusion: don't install bitbag/elasticsearch-plugin v1.0.1
    - Conclusion: remove pagerfanta/pagerfanta v2.0.1
    - Installation request for bitbag/elasticsearch-plugin ^1.0 -> satisfiable by bitbag/elasticsearch-plugin[v1.0.0, v1.0.1].
    - Can only install one of: pagerfanta/pagerfanta[v1.0.5, v2.0.1].
    - Can only install one of: pagerfanta/pagerfanta[v1.1.0, v2.0.1].
    - Installation request for pagerfanta/pagerfanta (locked at v2.0.1) -> satisfiable by pagerfanta/pagerfanta[v2.0.1].

**Comment by damonsson** [comment]
Problem is because Sylius-Standard (from 1.1.6) had installed pagerfanta/pagerfanta in `v2.0.1`. Plugin uses FriendsOfSymfony/FOSElasticaBundle which allows only `^1.0.5`. 

Solution: do `composer update pagerfanta/pagerfanta` that downgrade it to `v1.1.0` and installation Plugin will be possible again.

**Comment by jcgdjob** [comment]
Thanks! I have Installed but cannot see the filtering options after running
bin/console fos:elastica:populate

Resetting bitbag_shop_product
  0/60 [>---------------------------]   0%
%message%
 60/60 [============================] 100%
Populating bitbag_shop_product/defaultRefreshing bitbag_shop_product
Refreshing bitbag_shop_product
Resetting bitbag_option_taxons

 64/64 [============================] 100%
Populating bitbag_shop_product/default 0/4 [>---------------------------]   0%
%message%
 4/4 [============================] 100%
Populating bitbag_option_taxons/defaultRefreshing bitbag_option_taxons
Refreshing bitbag_option_taxons
Resetting bitbag_attribute_taxons

 74/74 [============================] 100%
Populating bitbag_shop_product/default
 14/14 [============================] 100%
Populating bitbag_option_taxons/default  0/10 [>---------------------------]   0%
%message%
 10/10 [============================] 100%
Populating bitbag_attribute_taxons/defaultRefreshing bitbag_attribute_taxons
Refreshing bitbag_attribute_taxons

Any ideas? (Sorry, I am new to Sylius and Symfony)
