### ISSUE TITLE
Elasticsearch data not populated when adding new ProductVariant

### ISSUE THREAD

**Issue by Holicz** [BitBagCommerce/SyliusElasticsearchPlugin#80]
### Steps to reproduce:

1. Create new product option
2. Create new configurable product
2a. Turn on the channel, enable at least one product option, assign the product to a taxon
3. Save the product
3a. The product **is not** displayed on category detail (correct behavior, because it has no variants)
4. Create and save variant for this product

### Result
The product **is still not** displayed on category detail

### Expected result
Be able to list the product.

When running command `bin/console fos:elastica:populate` the product appears. I guess it's a wrong config when elastica should populate.

**Comment by damonsson** [comment]
@Holicz which version of SyliusElasticsearchPlugin?

**Comment by Holicz** [comment]
It's v1.5.1

**Comment by bitbager** [comment]
Switch to the newest version. It supports synchronization between Doctrine entities and Elasticsearch data representation.

**Comment by jbcr** [comment]
Hi @bitbager,

I have the same issue with the v1.6.0. What is the new version that must be used to fix?
