### ISSUE TITLE
Taxons with no products are not indexed causing error when accessing index page

### ISSUE THREAD

**Issue by olia-bn** [BitBagCommerce/SyliusElasticsearchPlugin#81]
Taxons with no products do not seem to have a matching index in `bitbag_shop_products_{env}`.

This results in `No mapping found for [taxon_position_{taxon}] in order to sort on [index: bitbag_shop_products_{env}] [reason: all shards failed]` error when accessing the taxon's index page.

**Comment by damonsson** [comment]
fixed by #82
