### ISSUE TITLE
Products from Taxon with code containing tiret not displayed

### ISSUE THREAD

**Issue by F-Locos** [BitBagCommerce/SyliusElasticsearchPlugin#87]
Hi there,

Today, I wasted my morning on an unknow problem. But I finally found the solution.

I explain the problem : 
- I've some taxons, with somes products inside.
- The code of my taxons are set like this : brandname-parenttaxon-taxon (i.e: mareld-lampe-frontale).
- I populate to be sure than elasticsearch got it.
- I go to my 'mareld-lampe-frontale' taxon products list, and it show me : 'No products available'

The solution : 👍 
- Change the `-` by `_` 
- php bin/console fos:e:pop
- It's now showing the products.

The problem is than there's no errors catched. The problem is maybe from FOSElastica ?

If you need further information, don't hesitate to ping me.

**Comment by bitbager** [comment]
We mention in a bold font of the README not to use dashes. It's a problem related to Elasticsearch. There's a lot of valuable tips and use-cases in the README as well as on the Medium blog post mentioned in it. Take some time to study it, I guess it'll save much of your time :)

```
Be aware! Elasticsearch does not handle dashes well. This plugin depends on the code field in Sylius resources. Please use underscores instead of dashes in your code fields.
```

**Comment by F-Locos** [comment]
> We mention in a bold font of the README not to use dashes. It's a problem related to Elasticsearch. There's a lot of valuable tips and use-cases in the README as well as on the Medium blog post mentioned in it. Take some time to study it, I guess it'll save much of your time :)

Efffectively, it's a long time now I'm using your plug-in and never seen this caution before. My bad, sorry to make you lost your time!
