### ISSUE TITLE
Include attributes/options filter

### ISSUE THREAD

**Issue by ghost** [BitBagCommerce/SyliusElasticsearchPlugin#95]
Hi!

Like the two existing parameters :
- bitbag_es_excluded_filter_options
- bitbag_es_excluded_filter_attributes

It may be useful to have the opposite : 
- bitbag_es_included_filter_options
- bitbag_es_included_filter_attributes

Why ? 
Because I've too much attributes than I doesn't want to show and should be more simple if we can use included filter instead of excluded.
Or the possibility to choose which type we want to use.

It's also not good after adding other products with some new attributes/options. If we're not there (developpers), they'll can't manage that by themself.

Else how do you manage it for a huge size of products ? 
Because it's always simple products with few attributes/options on the demo of sylius/bitbag shop.

**Comment by leszczuu** [comment]
This has changed with new version - v4.0.2.
There is still only exclusion filter as a parameter, but it only shows filters relevant to results using facet search feature of elasticsearch. 
Inclusion based approach can be handled by disabling autodiscovery, and manually registering filters - this is dicussed in docs now: - https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/tree/master?tab=readme-ov-file#excluding-options-and-attributes-in-the-filter-menu under 'Example of manual registration of filters:'

Closing this issue as no longer relevant.
